services:  
  php:  
    image: runyf/hs-admin:v1.0
    container_name: hs-admin  
    network_mode: bridge
    restart: unless-stopped  
    ports:  
      - "8011:8000"  
    volumes:  
      - ~/hs-admin/think-app:/var/www/html
      - ~/headscale/config:/headscale/config
      - ~/headscale/data:/headscale/data
    environment:
      - TZ=Asia/Shanghai
