services:  
  php:  
    image: runyf/hs-admin
    container_name: hs-admin  
    network_mode: bridge
    restart: unless-stopped  
    ports:  
      - "8011:8000"  
    volumes:  
      - ~/hs-admin/think-app:/var/www/html
    environment:
      - TZ=Asia/Shanghai
