services:  
  nginx:  
    image: nginx:1.27.1-alpine3.20-perl
    container_name: nginx  
    restart: unless-stopped  
    network_mode: bridge
    ports:  
      - "80:80"  
      - "443:443"  
    volumes:  
      - ~/nginx/nginx.conf:/etc/nginx/nginx.conf  
      - ~/nginx/conf.d:/etc/nginx/conf.d  
      - ~/nginx/ssl:/etc/nginx/ssl  
      - ~/nginx/log:/var/log/nginx  
      - ~/nginx/html:/usr/share/nginx/html  
  
