services:  
  postgres-container:  
    image: postgres:14
    container_name: postgres
    environment:  
      POSTGRES_PASSWORD: pVMnj2IXMtXcfmFTgVI8F8uxLNAiLXphxhgwPs  
    ports:  
      - "5432:5432"  
    restart: unless-stopped  
    volumes:  
      - ~/postgres/data:/var/lib/postgresql/data/